import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

part 'user_model.freezed.dart';
part 'user_model.g.dart';

/// Represents the application user model.
///
/// Contains authentication and subscription details for a user.
@freezed
sealed class AppUser with _$AppUser {
  const factory AppUser({
    /// Unique identifier for the user.
    required String uid,

    /// Primary email address.
    required String email,

    /// User's display name, may be null if not set during registration.
    String? displayName,

    /// Profile photo URL, may be null if no photo is uploaded.
    String? photoUrl,

    /// Timestamp when the account was created.
    required DateTime createdAt,

    /// Timestamp of the last successful login.
    required DateTime lastLoginAt,

    /// Whether the user's email has been verified.
    @Default(false) bool isEmailVerified,

    /// Whether the user is signed in as a guest/anonymous.
    @Default(false) bool isAnonymous,

    /// Number of AI images generated by the user.
    @Default(0) int aiImagesGenerated,

    /// Current subscription tier (e.g., 'free', 'premium').
    String? subscriptionStatus,

    /// Billing interval (e.g., 'monthly', 'yearly').
    String? billingPeriod,

    /// Date when the current subscription period expires.
    DateTime? expiryDate,

    /// Date when the current subscription started.
    DateTime? subscriptionStartDate,
    /// Whether the user has disabled their account.
    @Default(false) bool isAccountDisabled,
  }) = _AppUser;

  /// Creates an [AppUser] from a JSON map.
  factory AppUser.fromJson(Map<String, dynamic> json) => _$AppUserFromJson(json);

  /// Creates an [AppUser] from a Firebase [User] object.
  factory AppUser.fromFirebase(dynamic user) {
    return AppUser(
      uid: user.uid,
      email: user.email ?? '',
      displayName: user.displayName,
      photoUrl: user.photoURL,
      createdAt: user.metadata.creationTime ?? DateTime.now(),
      lastLoginAt: user.metadata.lastSignInTime ?? DateTime.now(),
      isEmailVerified: user.emailVerified,
      isAnonymous: user.isAnonymous,
    );
  }

  /// Creates an [AppUser] from a Firestore [DocumentSnapshot].
  factory AppUser.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>? ?? {};
    
    DateTime parseDateTime(dynamic value) {
      if (value is Timestamp) return value.toDate();
      if (value is String) return DateTime.tryParse(value) ?? DateTime.now();
      return DateTime.now();
    }

    DateTime? parseDateTimeNullable(dynamic value) {
      if (value == null) return null;
      if (value is Timestamp) return value.toDate();
      if (value is String) return DateTime.tryParse(value);
      return null;
    }

    return AppUser(
      uid: doc.id,
      email: data['email'] ?? '',
      displayName: data['displayName'],
      photoUrl: data['photoUrl'],
      createdAt: parseDateTime(data['createdAt']),
      lastLoginAt: parseDateTime(data['lastLoginAt']),
      isEmailVerified: data['isEmailVerified'] ?? false,
      isAnonymous: data['isAnonymous'] ?? false,
      aiImagesGenerated: (data['aiImagesGenerated'] as num?)?.toInt() ?? 0,
      subscriptionStatus: data['subscriptionStatus'],
      billingPeriod: data['billingPeriod'],
      expiryDate: parseDateTimeNullable(data['expiryDate']),
      subscriptionStartDate: parseDateTimeNullable(data['subscriptionStartDate']),
      isAccountDisabled: data['isAccountDisabled'] ?? false,
    );
  }
}
