// dart format width=80
// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'user_model.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

// dart format off
T _$identity<T>(T value) => value;

/// @nodoc
mixin _$AppUser {

/// Unique identifier for the user.
 String get uid;/// Primary email address.
 String get email;/// User's display name, may be null if not set during registration.
 String? get displayName;/// Profile photo URL, may be null if no photo is uploaded.
 String? get photoUrl;/// Timestamp when the account was created.
 DateTime get createdAt;/// Timestamp of the last successful login.
 DateTime get lastLoginAt;/// Whether the user's email has been verified.
 bool get isEmailVerified;/// Whether the user is signed in as a guest/anonymous.
 bool get isAnonymous;/// Number of AI images generated by the user.
 int get aiImagesGenerated;/// Current subscription tier (e.g., 'free', 'premium').
 String? get subscriptionStatus;/// Billing interval (e.g., 'monthly', 'yearly').
 String? get billingPeriod;/// Date when the current subscription period expires.
 DateTime? get expiryDate;/// Date when the current subscription started.
 DateTime? get subscriptionStartDate;/// Whether the user has disabled their account.
 bool get isAccountDisabled;
/// Create a copy of AppUser
/// with the given fields replaced by the non-null parameter values.
@JsonKey(includeFromJson: false, includeToJson: false)
@pragma('vm:prefer-inline')
$AppUserCopyWith<AppUser> get copyWith => _$AppUserCopyWithImpl<AppUser>(this as AppUser, _$identity);

  /// Serializes this AppUser to a JSON map.
  Map<String, dynamic> toJson();


@override
bool operator ==(Object other) {
  return identical(this, other) || (other.runtimeType == runtimeType&&other is AppUser&&(identical(other.uid, uid) || other.uid == uid)&&(identical(other.email, email) || other.email == email)&&(identical(other.displayName, displayName) || other.displayName == displayName)&&(identical(other.photoUrl, photoUrl) || other.photoUrl == photoUrl)&&(identical(other.createdAt, createdAt) || other.createdAt == createdAt)&&(identical(other.lastLoginAt, lastLoginAt) || other.lastLoginAt == lastLoginAt)&&(identical(other.isEmailVerified, isEmailVerified) || other.isEmailVerified == isEmailVerified)&&(identical(other.isAnonymous, isAnonymous) || other.isAnonymous == isAnonymous)&&(identical(other.aiImagesGenerated, aiImagesGenerated) || other.aiImagesGenerated == aiImagesGenerated)&&(identical(other.subscriptionStatus, subscriptionStatus) || other.subscriptionStatus == subscriptionStatus)&&(identical(other.billingPeriod, billingPeriod) || other.billingPeriod == billingPeriod)&&(identical(other.expiryDate, expiryDate) || other.expiryDate == expiryDate)&&(identical(other.subscriptionStartDate, subscriptionStartDate) || other.subscriptionStartDate == subscriptionStartDate)&&(identical(other.isAccountDisabled, isAccountDisabled) || other.isAccountDisabled == isAccountDisabled));
}

@JsonKey(includeFromJson: false, includeToJson: false)
@override
int get hashCode => Object.hash(runtimeType,uid,email,displayName,photoUrl,createdAt,lastLoginAt,isEmailVerified,isAnonymous,aiImagesGenerated,subscriptionStatus,billingPeriod,expiryDate,subscriptionStartDate,isAccountDisabled);

@override
String toString() {
  return 'AppUser(uid: $uid, email: $email, displayName: $displayName, photoUrl: $photoUrl, createdAt: $createdAt, lastLoginAt: $lastLoginAt, isEmailVerified: $isEmailVerified, isAnonymous: $isAnonymous, aiImagesGenerated: $aiImagesGenerated, subscriptionStatus: $subscriptionStatus, billingPeriod: $billingPeriod, expiryDate: $expiryDate, subscriptionStartDate: $subscriptionStartDate, isAccountDisabled: $isAccountDisabled)';
}


}

/// @nodoc
abstract mixin class $AppUserCopyWith<$Res>  {
  factory $AppUserCopyWith(AppUser value, $Res Function(AppUser) _then) = _$AppUserCopyWithImpl;
@useResult
$Res call({
 String uid, String email, String? displayName, String? photoUrl, DateTime createdAt, DateTime lastLoginAt, bool isEmailVerified, bool isAnonymous, int aiImagesGenerated, String? subscriptionStatus, String? billingPeriod, DateTime? expiryDate, DateTime? subscriptionStartDate, bool isAccountDisabled
});




}
/// @nodoc
class _$AppUserCopyWithImpl<$Res>
    implements $AppUserCopyWith<$Res> {
  _$AppUserCopyWithImpl(this._self, this._then);

  final AppUser _self;
  final $Res Function(AppUser) _then;

/// Create a copy of AppUser
/// with the given fields replaced by the non-null parameter values.
@pragma('vm:prefer-inline') @override $Res call({Object? uid = null,Object? email = null,Object? displayName = freezed,Object? photoUrl = freezed,Object? createdAt = null,Object? lastLoginAt = null,Object? isEmailVerified = null,Object? isAnonymous = null,Object? aiImagesGenerated = null,Object? subscriptionStatus = freezed,Object? billingPeriod = freezed,Object? expiryDate = freezed,Object? subscriptionStartDate = freezed,Object? isAccountDisabled = null,}) {
  return _then(_self.copyWith(
uid: null == uid ? _self.uid : uid // ignore: cast_nullable_to_non_nullable
as String,email: null == email ? _self.email : email // ignore: cast_nullable_to_non_nullable
as String,displayName: freezed == displayName ? _self.displayName : displayName // ignore: cast_nullable_to_non_nullable
as String?,photoUrl: freezed == photoUrl ? _self.photoUrl : photoUrl // ignore: cast_nullable_to_non_nullable
as String?,createdAt: null == createdAt ? _self.createdAt : createdAt // ignore: cast_nullable_to_non_nullable
as DateTime,lastLoginAt: null == lastLoginAt ? _self.lastLoginAt : lastLoginAt // ignore: cast_nullable_to_non_nullable
as DateTime,isEmailVerified: null == isEmailVerified ? _self.isEmailVerified : isEmailVerified // ignore: cast_nullable_to_non_nullable
as bool,isAnonymous: null == isAnonymous ? _self.isAnonymous : isAnonymous // ignore: cast_nullable_to_non_nullable
as bool,aiImagesGenerated: null == aiImagesGenerated ? _self.aiImagesGenerated : aiImagesGenerated // ignore: cast_nullable_to_non_nullable
as int,subscriptionStatus: freezed == subscriptionStatus ? _self.subscriptionStatus : subscriptionStatus // ignore: cast_nullable_to_non_nullable
as String?,billingPeriod: freezed == billingPeriod ? _self.billingPeriod : billingPeriod // ignore: cast_nullable_to_non_nullable
as String?,expiryDate: freezed == expiryDate ? _self.expiryDate : expiryDate // ignore: cast_nullable_to_non_nullable
as DateTime?,subscriptionStartDate: freezed == subscriptionStartDate ? _self.subscriptionStartDate : subscriptionStartDate // ignore: cast_nullable_to_non_nullable
as DateTime?,isAccountDisabled: null == isAccountDisabled ? _self.isAccountDisabled : isAccountDisabled // ignore: cast_nullable_to_non_nullable
as bool,
  ));
}

}


/// @nodoc
@JsonSerializable()

class _AppUser implements AppUser {
  const _AppUser({required this.uid, required this.email, this.displayName, this.photoUrl, required this.createdAt, required this.lastLoginAt, this.isEmailVerified = false, this.isAnonymous = false, this.aiImagesGenerated = 0, this.subscriptionStatus, this.billingPeriod, this.expiryDate, this.subscriptionStartDate, this.isAccountDisabled = false});
  factory _AppUser.fromJson(Map<String, dynamic> json) => _$AppUserFromJson(json);

/// Unique identifier for the user.
@override final  String uid;
/// Primary email address.
@override final  String email;
/// User's display name, may be null if not set during registration.
@override final  String? displayName;
/// Profile photo URL, may be null if no photo is uploaded.
@override final  String? photoUrl;
/// Timestamp when the account was created.
@override final  DateTime createdAt;
/// Timestamp of the last successful login.
@override final  DateTime lastLoginAt;
/// Whether the user's email has been verified.
@override@JsonKey() final  bool isEmailVerified;
/// Whether the user is signed in as a guest/anonymous.
@override@JsonKey() final  bool isAnonymous;
/// Number of AI images generated by the user.
@override@JsonKey() final  int aiImagesGenerated;
/// Current subscription tier (e.g., 'free', 'premium').
@override final  String? subscriptionStatus;
/// Billing interval (e.g., 'monthly', 'yearly').
@override final  String? billingPeriod;
/// Date when the current subscription period expires.
@override final  DateTime? expiryDate;
/// Date when the current subscription started.
@override final  DateTime? subscriptionStartDate;
/// Whether the user has disabled their account.
@override@JsonKey() final  bool isAccountDisabled;

/// Create a copy of AppUser
/// with the given fields replaced by the non-null parameter values.
@override @JsonKey(includeFromJson: false, includeToJson: false)
@pragma('vm:prefer-inline')
_$AppUserCopyWith<_AppUser> get copyWith => __$AppUserCopyWithImpl<_AppUser>(this, _$identity);

@override
Map<String, dynamic> toJson() {
  return _$AppUserToJson(this, );
}

@override
bool operator ==(Object other) {
  return identical(this, other) || (other.runtimeType == runtimeType&&other is _AppUser&&(identical(other.uid, uid) || other.uid == uid)&&(identical(other.email, email) || other.email == email)&&(identical(other.displayName, displayName) || other.displayName == displayName)&&(identical(other.photoUrl, photoUrl) || other.photoUrl == photoUrl)&&(identical(other.createdAt, createdAt) || other.createdAt == createdAt)&&(identical(other.lastLoginAt, lastLoginAt) || other.lastLoginAt == lastLoginAt)&&(identical(other.isEmailVerified, isEmailVerified) || other.isEmailVerified == isEmailVerified)&&(identical(other.isAnonymous, isAnonymous) || other.isAnonymous == isAnonymous)&&(identical(other.aiImagesGenerated, aiImagesGenerated) || other.aiImagesGenerated == aiImagesGenerated)&&(identical(other.subscriptionStatus, subscriptionStatus) || other.subscriptionStatus == subscriptionStatus)&&(identical(other.billingPeriod, billingPeriod) || other.billingPeriod == billingPeriod)&&(identical(other.expiryDate, expiryDate) || other.expiryDate == expiryDate)&&(identical(other.subscriptionStartDate, subscriptionStartDate) || other.subscriptionStartDate == subscriptionStartDate)&&(identical(other.isAccountDisabled, isAccountDisabled) || other.isAccountDisabled == isAccountDisabled));
}

@JsonKey(includeFromJson: false, includeToJson: false)
@override
int get hashCode => Object.hash(runtimeType,uid,email,displayName,photoUrl,createdAt,lastLoginAt,isEmailVerified,isAnonymous,aiImagesGenerated,subscriptionStatus,billingPeriod,expiryDate,subscriptionStartDate,isAccountDisabled);

@override
String toString() {
  return 'AppUser(uid: $uid, email: $email, displayName: $displayName, photoUrl: $photoUrl, createdAt: $createdAt, lastLoginAt: $lastLoginAt, isEmailVerified: $isEmailVerified, isAnonymous: $isAnonymous, aiImagesGenerated: $aiImagesGenerated, subscriptionStatus: $subscriptionStatus, billingPeriod: $billingPeriod, expiryDate: $expiryDate, subscriptionStartDate: $subscriptionStartDate, isAccountDisabled: $isAccountDisabled)';
}


}

/// @nodoc
abstract mixin class _$AppUserCopyWith<$Res> implements $AppUserCopyWith<$Res> {
  factory _$AppUserCopyWith(_AppUser value, $Res Function(_AppUser) _then) = __$AppUserCopyWithImpl;
@override @useResult
$Res call({
 String uid, String email, String? displayName, String? photoUrl, DateTime createdAt, DateTime lastLoginAt, bool isEmailVerified, bool isAnonymous, int aiImagesGenerated, String? subscriptionStatus, String? billingPeriod, DateTime? expiryDate, DateTime? subscriptionStartDate, bool isAccountDisabled
});




}
/// @nodoc
class __$AppUserCopyWithImpl<$Res>
    implements _$AppUserCopyWith<$Res> {
  __$AppUserCopyWithImpl(this._self, this._then);

  final _AppUser _self;
  final $Res Function(_AppUser) _then;

/// Create a copy of AppUser
/// with the given fields replaced by the non-null parameter values.
@override @pragma('vm:prefer-inline') $Res call({Object? uid = null,Object? email = null,Object? displayName = freezed,Object? photoUrl = freezed,Object? createdAt = null,Object? lastLoginAt = null,Object? isEmailVerified = null,Object? isAnonymous = null,Object? aiImagesGenerated = null,Object? subscriptionStatus = freezed,Object? billingPeriod = freezed,Object? expiryDate = freezed,Object? subscriptionStartDate = freezed,Object? isAccountDisabled = null,}) {
  return _then(_AppUser(
uid: null == uid ? _self.uid : uid // ignore: cast_nullable_to_non_nullable
as String,email: null == email ? _self.email : email // ignore: cast_nullable_to_non_nullable
as String,displayName: freezed == displayName ? _self.displayName : displayName // ignore: cast_nullable_to_non_nullable
as String?,photoUrl: freezed == photoUrl ? _self.photoUrl : photoUrl // ignore: cast_nullable_to_non_nullable
as String?,createdAt: null == createdAt ? _self.createdAt : createdAt // ignore: cast_nullable_to_non_nullable
as DateTime,lastLoginAt: null == lastLoginAt ? _self.lastLoginAt : lastLoginAt // ignore: cast_nullable_to_non_nullable
as DateTime,isEmailVerified: null == isEmailVerified ? _self.isEmailVerified : isEmailVerified // ignore: cast_nullable_to_non_nullable
as bool,isAnonymous: null == isAnonymous ? _self.isAnonymous : isAnonymous // ignore: cast_nullable_to_non_nullable
as bool,aiImagesGenerated: null == aiImagesGenerated ? _self.aiImagesGenerated : aiImagesGenerated // ignore: cast_nullable_to_non_nullable
as int,subscriptionStatus: freezed == subscriptionStatus ? _self.subscriptionStatus : subscriptionStatus // ignore: cast_nullable_to_non_nullable
as String?,billingPeriod: freezed == billingPeriod ? _self.billingPeriod : billingPeriod // ignore: cast_nullable_to_non_nullable
as String?,expiryDate: freezed == expiryDate ? _self.expiryDate : expiryDate // ignore: cast_nullable_to_non_nullable
as DateTime?,subscriptionStartDate: freezed == subscriptionStartDate ? _self.subscriptionStartDate : subscriptionStartDate // ignore: cast_nullable_to_non_nullable
as DateTime?,isAccountDisabled: null == isAccountDisabled ? _self.isAccountDisabled : isAccountDisabled // ignore: cast_nullable_to_non_nullable
as bool,
  ));
}


}

// dart format on
